2022-03-30 17:47:56,304:DEBUG:The directories has been created
2022-03-31 23:54:49,459:DEBUG:The directories has been created
2022-03-31 23:56:04,275:DEBUG:The file has not been found
2022-03-31 23:56:04,280:DEBUG:Starting new HTTPS connection (1): datos.gob.ar:443
2022-03-31 23:56:09,225:DEBUG:https://datos.gob.ar:443 "GET /dataset/cultura-mapa-cultural-espacios-culturales/archivo/cultura_4207def0-2ff7-41d5-9095-d42ae8207a5d HTTP/1.1" 200 10180
2022-03-31 23:56:09,226:ERROR:There has been an exception: {e}
Traceback (most recent call last):
  File "/tmp/ipykernel_3040/772795067.py", line 19, in <cell line: 17>
    open(f'museums/{year}-{month}/ museums-{day}-{month}-{year}.csv''wb').write(rMuseum.content)
FileNotFoundError: [Errno 2] No such file or directory: 'museums/2022-March/ museums-31-March-2022.csvwb'
2022-03-31 23:59:32,232:DEBUG:The file has not been found
2022-03-31 23:59:32,234:DEBUG:Starting new HTTPS connection (1): datos.gob.ar:443
2022-03-31 23:59:42,927:DEBUG:https://datos.gob.ar:443 "GET /dataset/cultura-mapa-cultural-espacios-culturales/archivo/cultura_4207def0-2ff7-41d5-9095-d42ae8207a5d HTTP/1.1" 200 10169
2022-03-31 23:59:42,943:ERROR:There has been an exception: {e}
Traceback (most recent call last):
  File "/tmp/ipykernel_3040/4285722391.py", line 19, in <cell line: 16>
    open(f'museums/{year}-{month}/ museums-{day}-{month}-{year}.csv''wb').write(rMuseum.content)
FileNotFoundError: [Errno 2] No such file or directory: 'museums/2022-March/ museums-31-March-2022.csvwb'
2022-04-05 22:58:46,304:DEBUG:The directories has been created
2022-04-05 22:58:46,320:DEBUG:The file has not been found
2022-04-05 22:58:46,325:DEBUG:Starting new HTTPS connection (1): datos.gob.ar:443
2022-04-05 22:59:14,022:DEBUG:https://datos.gob.ar:443 "GET /dataset/cultura-mapa-cultural-espacios-culturales/archivo/cultura_4207def0-2ff7-41d5-9095-d42ae8207a5d HTTP/1.1" 200 10407
2022-04-05 22:59:14,024:ERROR:There has been an exception: {e}
Traceback (most recent call last):
  File "/tmp/ipykernel_3291/4285722391.py", line 19, in <cell line: 16>
    open(f'museums/{year}-{month}/ museums-{day}-{month}-{year}.csv''wb').write(rMuseum.content)
FileNotFoundError: [Errno 2] No such file or directory: 'museums/2022-April/ museums-05-April-2022.csvwb'
2022-04-05 22:59:21,435:DEBUG:The directories has been created
2022-04-05 22:59:21,448:DEBUG:The file has not been found
2022-04-05 22:59:21,451:DEBUG:Starting new HTTPS connection (1): datos.gob.ar:443
2022-04-05 22:59:43,215:DEBUG:https://datos.gob.ar:443 "GET /dataset/cultura-mapa-cultural-espacios-culturales/archivo/cultura_4207def0-2ff7-41d5-9095-d42ae8207a5d HTTP/1.1" 200 10388
2022-04-05 22:59:43,218:ERROR:There has been an exception: {e}
Traceback (most recent call last):
  File "/tmp/ipykernel_3363/4285722391.py", line 19, in <cell line: 16>
    open(f'museums/{year}-{month}/ museums-{day}-{month}-{year}.csv''wb').write(rMuseum.content)
FileNotFoundError: [Errno 2] No such file or directory: 'museums/2022-April/ museums-05-April-2022.csvwb'
2022-04-16 22:06:45,808:DEBUG:The directories has been created
2022-04-16 22:06:45,820:DEBUG:The file has not been found
2022-04-16 22:06:45,825:DEBUG:Starting new HTTPS connection (1): datos.gob.ar:443
2022-04-16 22:06:47,804:DEBUG:https://datos.gob.ar:443 "GET /dataset/cultura-mapa-cultural-espacios-culturales/archivo/cultura_4207def0-2ff7-41d5-9095-d42ae8207a5d HTTP/1.1" 200 10403
2022-04-16 22:06:47,806:ERROR:There has been an exception: {e}
Traceback (most recent call last):
  File "/tmp/ipykernel_4021/4285722391.py", line 19, in <cell line: 16>
    open(f'museums/{year}-{month}/ museums-{day}-{month}-{year}.csv''wb').write(rMuseum.content)
FileNotFoundError: [Errno 2] No such file or directory: 'museums/2022-April/ museums-16-April-2022.csvwb'
2022-04-17 00:52:45,615:DEBUG:La conexión se ha efectuado exitosamente :)
2022-04-17 00:52:55,348:DEBUG:La conexión se ha efectuado exitosamente :)
2022-04-17 00:53:00,744:DEBUG:La conexión se ha efectuado exitosamente :)
2022-04-17 00:53:22,258:DEBUG:Connection succesfull :)
2022-04-17 00:56:09,622:DEBUG:diff parser start
2022-04-17 00:56:09,622:DEBUG:line_lengths old: 2; new: 2
2022-04-17 00:56:09,623:DEBUG:-> code[equal] old[1:1] new[1:1]
2022-04-17 00:56:09,623:DEBUG:parse_part from 1 to 2 (to 1 in part parser)
2022-04-17 00:56:09,624:DEBUG:-> code[replace] old[2:2] new[2:2]
2022-04-17 00:56:09,624:DEBUG:diff parser end
2022-04-17 00:56:13,054:DEBUG:diff parser start
2022-04-17 00:56:13,054:DEBUG:line_lengths old: 2; new: 2
2022-04-17 00:56:13,054:DEBUG:-> code[equal] old[1:1] new[1:1]
2022-04-17 00:56:13,055:DEBUG:parse_part from 1 to 2 (to 1 in part parser)
2022-04-17 00:56:13,055:DEBUG:-> code[replace] old[2:2] new[2:2]
2022-04-17 00:56:13,055:DEBUG:diff parser end
2022-04-17 23:13:19,964:DEBUG:The directories has been created
2022-04-17 23:13:19,987:DEBUG:The file has not been found
2022-04-17 23:13:19,993:DEBUG:Starting new HTTPS connection (1): datos.gob.ar:443
2022-04-17 23:13:22,557:DEBUG:https://datos.gob.ar:443 "GET /dataset/cultura-mapa-cultural-espacios-culturales/archivo/cultura_4207def0-2ff7-41d5-9095-d42ae8207a5d HTTP/1.1" 200 10416
2022-04-17 23:13:22,559:ERROR:There has been an exception: {e}
Traceback (most recent call last):
  File "/tmp/ipykernel_3860/4285722391.py", line 19, in <cell line: 16>
    open(f'museums/{year}-{month}/ museums-{day}-{month}-{year}.csv''wb').write(rMuseum.content)
FileNotFoundError: [Errno 2] No such file or directory: 'museums/2022-April/ museums-17-April-2022.csvwb'
2022-04-17 23:13:22,568:DEBUG:Connection succesfull :)
2022-04-19 11:02:37,315:DEBUG:The directories has been created
2022-04-19 11:02:37,344:DEBUG:The file has not been found
2022-04-19 11:02:37,359:DEBUG:Starting new HTTPS connection (1): datos.gob.ar:443
2022-04-19 11:02:48,512:DEBUG:https://datos.gob.ar:443 "GET /dataset/cultura-mapa-cultural-espacios-culturales/archivo/cultura_4207def0-2ff7-41d5-9095-d42ae8207a5d HTTP/1.1" 200 10415
2022-04-19 11:02:48,519:ERROR:There has been an exception: [Errno 2] No such file or directory: 'museums/2022-April/ museums-19-April-2022.csvwb'
Traceback (most recent call last):
  File "/tmp/ipykernel_4437/1389225065.py", line 19, in <cell line: 16>
    open(f'museums/{year}-{month}/ museums-{day}-{month}-{year}.csv''wb').write(rMuseum.content)
FileNotFoundError: [Errno 2] No such file or directory: 'museums/2022-April/ museums-19-April-2022.csvwb'
2022-04-19 11:02:48,534:DEBUG:Connection succesfull :)
2022-04-19 11:09:13,776:DEBUG:The directories has been created
2022-04-19 11:09:13,797:DEBUG:The file has not been found
2022-04-19 11:09:13,800:DEBUG:Starting new HTTPS connection (1): datos.gob.ar:443
2022-04-19 11:10:09,279:DEBUG:https://datos.gob.ar:443 "GET /dataset/cultura-mapa-cultural-espacios-culturales/archivo/cultura_4207def0-2ff7-41d5-9095-d42ae8207a5d HTTP/1.1" 200 10408
2022-04-19 11:10:09,287:ERROR:There has been an exception: [Errno 2] No such file or directory: 'museums/2022-April/ museums-19-April-2022.csvwb'
Traceback (most recent call last):
  File "/tmp/ipykernel_4684/1389225065.py", line 19, in <cell line: 16>
    open(f'museums/{year}-{month}/ museums-{day}-{month}-{year}.csv''wb').write(rMuseum.content)
FileNotFoundError: [Errno 2] No such file or directory: 'museums/2022-April/ museums-19-April-2022.csvwb'
2022-04-19 11:10:09,313:DEBUG:Connection succesfull :)
2022-04-19 11:12:01,579:DEBUG:The directories has been created
2022-04-19 11:12:01,594:DEBUG:The file has not been found
2022-04-19 11:12:01,599:DEBUG:Starting new HTTPS connection (1): datos.gob.ar:443
2022-04-19 11:12:31,868:DEBUG:https://datos.gob.ar:443 "GET /dataset/cultura-mapa-cultural-espacios-culturales/archivo/cultura_4207def0-2ff7-41d5-9095-d42ae8207a5d HTTP/1.1" 200 10412
2022-04-19 11:12:31,880:ERROR:There has been an exception: [Errno 2] No such file or directory: 'museums/2022-April/ museums-19-April-2022.csvwb'
Traceback (most recent call last):
  File "/tmp/ipykernel_4824/1389225065.py", line 19, in <cell line: 16>
    open(f'museums/{year}-{month}/ museums-{day}-{month}-{year}.csv''wb').write(rMuseum.content)
FileNotFoundError: [Errno 2] No such file or directory: 'museums/2022-April/ museums-19-April-2022.csvwb'
2022-04-19 11:12:31,902:DEBUG:Connection succesfull :)
2022-04-19 12:06:36,400:DEBUG:diff parser start
2022-04-19 12:06:36,403:DEBUG:line_lengths old: 2; new: 2
2022-04-19 12:06:36,403:DEBUG:-> code[equal] old[1:1] new[1:1]
2022-04-19 12:06:36,410:DEBUG:parse_part from 1 to 2 (to 1 in part parser)
2022-04-19 12:06:36,410:DEBUG:-> code[replace] old[2:2] new[2:2]
2022-04-19 12:06:36,410:DEBUG:diff parser end
2022-04-19 13:17:21,802:DEBUG:diff parser start
2022-04-19 13:17:21,802:DEBUG:line_lengths old: 2; new: 4
2022-04-19 13:17:21,802:DEBUG:-> code[equal] old[1:1] new[1:1]
2022-04-19 13:17:21,804:DEBUG:parse_part from 1 to 2 (to 3 in part parser)
2022-04-19 13:17:21,804:DEBUG:-> code[replace] old[2:2] new[2:4]
2022-04-19 13:17:21,805:DEBUG:parse_part from 3 to 4 (to 3 in part parser)
2022-04-19 13:17:21,805:DEBUG:diff parser end
2022-04-19 13:42:06,060:DEBUG:diff parser start
2022-04-19 13:42:06,061:DEBUG:line_lengths old: 4; new: 3
2022-04-19 13:42:06,061:DEBUG:-> code[equal] old[1:2] new[1:2]
2022-04-19 13:42:06,062:DEBUG:copy old[2:2] new[1:2]
2022-04-19 13:42:06,062:DEBUG:-> code[replace] old[3:4] new[3:3]
2022-04-19 13:42:06,062:DEBUG:parse_part from 3 to 3 (to 2 in part parser)
2022-04-19 13:42:06,062:DEBUG:diff parser end
2022-04-19 13:42:06,142:DEBUG:pickle loaded: /home/frank/.local/lib/python3.9/site-packages/jedi/third_party/typeshed/stdlib/3/builtins.pyi
2022-04-19 13:42:06,205:DEBUG:pickle loaded: /home/frank/.local/lib/python3.9/site-packages/jedi/third_party/typeshed/stdlib/3/sys.pyi
2022-04-19 14:10:06,999:DEBUG:diff parser start
2022-04-19 14:10:06,999:DEBUG:line_lengths old: 3; new: 2
2022-04-19 14:10:06,999:DEBUG:-> code[replace] old[1:3] new[1:2]
2022-04-19 14:10:07,000:DEBUG:parse_part from 1 to 2 (to 1 in part parser)
2022-04-19 14:10:07,000:DEBUG:diff parser end
2022-04-19 14:10:22,793:DEBUG:diff parser start
2022-04-19 14:10:22,794:DEBUG:line_lengths old: 2; new: 2
2022-04-19 14:10:22,795:DEBUG:-> code[equal] old[1:1] new[1:1]
2022-04-19 14:10:22,800:DEBUG:parse_part from 1 to 2 (to 1 in part parser)
2022-04-19 14:10:22,801:DEBUG:-> code[replace] old[2:2] new[2:2]
2022-04-19 14:10:22,801:DEBUG:diff parser end
2022-04-19 14:11:33,689:DEBUG:diff parser start
2022-04-19 14:11:33,690:DEBUG:line_lengths old: 2; new: 2
2022-04-19 14:11:33,690:DEBUG:-> code[equal] old[1:1] new[1:1]
2022-04-19 14:11:33,690:DEBUG:parse_part from 1 to 2 (to 1 in part parser)
2022-04-19 14:11:33,690:DEBUG:-> code[replace] old[2:2] new[2:2]
2022-04-19 14:11:33,691:DEBUG:diff parser end
2022-04-19 14:11:34,537:DEBUG:diff parser start
2022-04-19 14:11:34,538:DEBUG:line_lengths old: 2; new: 2
2022-04-19 14:11:34,538:DEBUG:-> code[equal] old[1:1] new[1:1]
2022-04-19 14:11:34,539:DEBUG:parse_part from 1 to 2 (to 1 in part parser)
2022-04-19 14:11:34,539:DEBUG:-> code[replace] old[2:2] new[2:2]
2022-04-19 14:11:34,539:DEBUG:diff parser end
2022-04-19 14:11:46,949:DEBUG:diff parser start
2022-04-19 14:11:46,949:DEBUG:line_lengths old: 2; new: 2
2022-04-19 14:11:46,950:DEBUG:-> code[equal] old[1:1] new[1:1]
2022-04-19 14:11:46,953:DEBUG:parse_part from 1 to 2 (to 1 in part parser)
2022-04-19 14:11:46,954:DEBUG:-> code[replace] old[2:2] new[2:2]
2022-04-19 14:11:46,954:DEBUG:diff parser end
2022-04-19 14:11:49,808:DEBUG:diff parser start
2022-04-19 14:11:49,809:DEBUG:line_lengths old: 2; new: 2
2022-04-19 14:11:49,809:DEBUG:-> code[equal] old[1:1] new[1:1]
2022-04-19 14:11:49,811:DEBUG:parse_part from 1 to 2 (to 1 in part parser)
2022-04-19 14:11:49,811:DEBUG:-> code[replace] old[2:2] new[2:2]
2022-04-19 14:11:49,811:DEBUG:diff parser end
2022-04-19 14:13:56,074:DEBUG:diff parser start
2022-04-19 14:13:56,075:DEBUG:line_lengths old: 2; new: 2
2022-04-19 14:13:56,075:DEBUG:-> code[equal] old[1:1] new[1:1]
2022-04-19 14:13:56,076:DEBUG:parse_part from 1 to 2 (to 1 in part parser)
2022-04-19 14:13:56,076:DEBUG:-> code[replace] old[2:2] new[2:2]
2022-04-19 14:13:56,076:DEBUG:diff parser end
2022-04-19 14:13:57,264:DEBUG:diff parser start
2022-04-19 14:13:57,265:DEBUG:line_lengths old: 2; new: 2
2022-04-19 14:13:57,266:DEBUG:-> code[equal] old[1:1] new[1:1]
2022-04-19 14:13:57,267:DEBUG:parse_part from 1 to 2 (to 1 in part parser)
2022-04-19 14:13:57,267:DEBUG:-> code[replace] old[2:2] new[2:2]
2022-04-19 14:13:57,267:DEBUG:diff parser end
2022-04-19 14:16:48,051:DEBUG:diff parser start
2022-04-19 14:16:48,052:DEBUG:line_lengths old: 2; new: 2
2022-04-19 14:16:48,053:DEBUG:-> code[replace] old[1:2] new[1:2]
2022-04-19 14:16:48,055:DEBUG:parse_part from 1 to 2 (to 1 in part parser)
2022-04-19 14:16:48,055:DEBUG:diff parser end
2022-04-19 14:16:54,947:DEBUG:diff parser start
2022-04-19 14:16:54,948:DEBUG:line_lengths old: 2; new: 2
2022-04-19 14:16:54,949:DEBUG:-> code[equal] old[1:1] new[1:1]
2022-04-19 14:16:54,950:DEBUG:parse_part from 1 to 2 (to 1 in part parser)
2022-04-19 14:16:54,950:DEBUG:-> code[replace] old[2:2] new[2:2]
2022-04-19 14:16:54,951:DEBUG:diff parser end
2022-04-19 14:16:58,994:DEBUG:diff parser start
2022-04-19 14:16:58,997:DEBUG:line_lengths old: 2; new: 2
2022-04-19 14:16:58,997:DEBUG:-> code[equal] old[1:1] new[1:1]
2022-04-19 14:16:58,997:DEBUG:parse_part from 1 to 2 (to 1 in part parser)
2022-04-19 14:16:58,997:DEBUG:-> code[replace] old[2:2] new[2:2]
2022-04-19 14:16:58,998:DEBUG:diff parser end
2022-04-19 14:17:01,574:DEBUG:diff parser start
2022-04-19 14:17:01,574:DEBUG:line_lengths old: 2; new: 2
2022-04-19 14:17:01,574:DEBUG:-> code[equal] old[1:1] new[1:1]
2022-04-19 14:17:01,575:DEBUG:parse_part from 1 to 2 (to 1 in part parser)
2022-04-19 14:17:01,575:DEBUG:-> code[replace] old[2:2] new[2:2]
2022-04-19 14:17:01,575:DEBUG:diff parser end
2022-04-19 14:18:22,859:DEBUG:diff parser start
2022-04-19 14:18:22,859:DEBUG:line_lengths old: 2; new: 2
2022-04-19 14:18:22,859:DEBUG:-> code[replace] old[1:2] new[1:2]
2022-04-19 14:18:22,860:DEBUG:parse_part from 1 to 2 (to 1 in part parser)
2022-04-19 14:18:22,860:DEBUG:diff parser end
2022-04-19 14:25:29,438:DEBUG:diff parser start
2022-04-19 14:25:29,438:DEBUG:line_lengths old: 2; new: 2
2022-04-19 14:25:29,438:DEBUG:-> code[replace] old[1:2] new[1:2]
2022-04-19 14:25:29,439:DEBUG:parse_part from 1 to 2 (to 1 in part parser)
2022-04-19 14:25:29,439:DEBUG:diff parser end
2022-04-19 14:25:34,850:DEBUG:diff parser start
2022-04-19 14:25:34,851:DEBUG:line_lengths old: 2; new: 2
2022-04-19 14:25:34,851:DEBUG:-> code[equal] old[1:1] new[1:1]
2022-04-19 14:25:34,855:DEBUG:parse_part from 1 to 2 (to 1 in part parser)
2022-04-19 14:25:34,857:DEBUG:-> code[replace] old[2:2] new[2:2]
2022-04-19 14:25:34,858:DEBUG:diff parser end
2022-04-19 14:25:40,698:DEBUG:diff parser start
2022-04-19 14:25:40,701:DEBUG:line_lengths old: 2; new: 2
2022-04-19 14:25:40,702:DEBUG:-> code[equal] old[1:1] new[1:1]
2022-04-19 14:25:40,704:DEBUG:parse_part from 1 to 2 (to 1 in part parser)
2022-04-19 14:25:40,704:DEBUG:-> code[replace] old[2:2] new[2:2]
2022-04-19 14:25:40,705:DEBUG:diff parser end
2022-04-19 14:27:55,277:DEBUG:The directories has been created
2022-04-19 14:27:55,307:DEBUG:The file has not been found
2022-04-19 14:27:55,313:DEBUG:Starting new HTTPS connection (1): datos.gob.ar:443
2022-04-19 14:27:58,759:DEBUG:https://datos.gob.ar:443 "GET /dataset/cultura-mapa-cultural-espacios-culturales/archivo/cultura_4207def0-2ff7-41d5-9095-d42ae8207a5d HTTP/1.1" 200 10389
2022-04-19 14:27:58,762:ERROR:There has been an exception: [Errno 2] No such file or directory: 'museums/2022-April/ museums-19-April-2022.csvwb'
Traceback (most recent call last):
  File "/tmp/ipykernel_9231/1389225065.py", line 19, in <cell line: 16>
    open(f'museums/{year}-{month}/ museums-{day}-{month}-{year}.csv''wb').write(rMuseum.content)
FileNotFoundError: [Errno 2] No such file or directory: 'museums/2022-April/ museums-19-April-2022.csvwb'
2022-04-19 14:27:58,785:DEBUG:Connection succesfull :)
2022-04-19 14:34:20,059:DEBUG:pickle loaded: /home/frank/.local/lib/python3.9/site-packages/jedi/third_party/typeshed/stdlib/3/builtins.pyi
2022-04-19 14:34:20,116:DEBUG:pickle loaded: /home/frank/.local/lib/python3.9/site-packages/jedi/third_party/typeshed/stdlib/3/sys.pyi
2022-04-19 14:36:16,798:DEBUG:diff parser start
2022-04-19 14:36:16,800:DEBUG:line_lengths old: 1; new: 1
2022-04-19 14:36:16,801:DEBUG:-> code[replace] old[1:1] new[1:1]
2022-04-19 14:36:16,802:DEBUG:parse_part from 1 to 1 (to 0 in part parser)
2022-04-19 14:36:16,803:DEBUG:diff parser end
2022-04-19 14:37:03,617:DEBUG:diff parser start
2022-04-19 14:37:03,618:DEBUG:line_lengths old: 1; new: 3
2022-04-19 14:37:03,618:DEBUG:-> code[replace] old[1:1] new[1:3]
2022-04-19 14:37:03,618:DEBUG:parse_part from 1 to 3 (to 2 in part parser)
2022-04-19 14:37:03,618:DEBUG:diff parser end
2022-04-19 14:37:18,569:DEBUG:diff parser start
2022-04-19 14:37:18,569:DEBUG:line_lengths old: 3; new: 4
2022-04-19 14:37:18,569:DEBUG:-> code[equal] old[1:2] new[1:2]
2022-04-19 14:37:18,570:DEBUG:parse_part from 1 to 3 (to 3 in part parser)
2022-04-19 14:37:18,571:DEBUG:-> code[replace] old[3:3] new[3:4]
2022-04-19 14:37:18,571:DEBUG:parse_part from 4 to 4 (to 3 in part parser)
2022-04-19 14:37:18,571:DEBUG:diff parser end
2022-04-19 14:37:20,245:DEBUG:diff parser start
2022-04-19 14:37:20,250:DEBUG:line_lengths old: 4; new: 4
2022-04-19 14:37:20,250:DEBUG:-> code[equal] old[1:3] new[1:3]
2022-04-19 14:37:20,250:DEBUG:copy old[3:3] new[1:3]
2022-04-19 14:37:20,251:DEBUG:-> code[replace] old[4:4] new[4:4]
2022-04-19 14:37:20,251:DEBUG:parse_part from 4 to 4 (to 3 in part parser)
2022-04-19 14:37:20,252:DEBUG:diff parser end
2022-04-20 21:51:20,210:DEBUG:The directories has been created
2022-04-20 21:51:20,223:DEBUG:The file has not been found
2022-04-20 21:51:20,228:DEBUG:Starting new HTTPS connection (1): datos.gob.ar:443
2022-04-20 21:51:24,436:DEBUG:https://datos.gob.ar:443 "GET /dataset/cultura-mapa-cultural-espacios-culturales/archivo/cultura_4207def0-2ff7-41d5-9095-d42ae8207a5d HTTP/1.1" 200 10414
2022-04-20 21:51:24,438:ERROR:There has been an exception: [Errno 2] No such file or directory: 'museums/2022-April/ museums-20-April-2022.csvwb'
Traceback (most recent call last):
  File "/tmp/ipykernel_4191/1389225065.py", line 19, in <cell line: 16>
    open(f'museums/{year}-{month}/ museums-{day}-{month}-{year}.csv''wb').write(rMuseum.content)
FileNotFoundError: [Errno 2] No such file or directory: 'museums/2022-April/ museums-20-April-2022.csvwb'
2022-04-20 21:51:24,449:DEBUG:Connection succesfull :)
